server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: aditya8210@
  url: jdbc:mysql://localhost:3306/tasktracker
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.hbm2ddl.auto: validate
    hibernate.show_sql: true
    hibernate.format_sql: true
